import "./globals.css";
import {Metadata} from "next";
import React from 'react';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactElement; }>) {
    return (
        <html lang="en">
        <body>{children}</body>
        </html>
    );
}
